version: "@latest"
base_url: http://localhost:8080
server: 
  http:
    address: :8080
  grpc:
    address: :8081
resource:
  sql_database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db_name: postgres
  redis:
    address: localhost:6379
  # sql_database:
  #   host: localhost
  #   port: 5433
  #   user: yugabyte
  #   password: yugabyte
  #   db_name: yugabyte
  # otel_collector:
  #   otlp/grpc: localhost:4317