version: "@latest"
port: 8080
resource:
  sql_database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    db_name: postgres
  redis:
    address: localhost:6379
  otel_collector:
    otlp/grpc: localhost:4317