apiVersion: apps/v1
kind: Deployment
metadata:
  name: bimble-backend-depl
  namespace: bimble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bimble-backend-pod
  template:
    metadata:
      labels:
        app: bimble-backend-pod
    spec:
      containers:
        - name: bimble-backend
          image: 0.0.0.0:30001/bimble-backend:#{RELEASE_VERSION}
          imagePullPolicy: Always
          command: ['./bin/app-api', '-config=./files/config/prod.yaml']
          envFrom:
            - secretRef:
                name: bimble-backend