apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: bimble-dev
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlp/uptrace:
        endpoint: my-uptrace.uptrace.svc.cluster.local:14317
        tls:
          insecure: true
        headers:
          uptrace-dsn: 'http://project1_secret_token@localhost:14318?grpc=14317'
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace]