name: "Release to Development"
concurrency:
  group: dev
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Replace env placeholders
        run: |
          sed -i "s/#{GITHUB_SHA}/$GITHUB_SHA/g" ./.k8s/dev/bimble-backend-depl.yaml
          sed -i "s/#{VERSION}/$GITHUB_SHA/g" ./Makefile
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker build -t huseinnashr/bimble-backend:${GITHUB_SHA}-dev .
      - run: docker push huseinnashr/bimble-backend:${GITHUB_SHA}-dev
      - name: Deploy to Dev Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_PROD }}
        with:
          args: |
            kubectl apply -f ./.k8s/dev/bimble-backend-depl.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-svc.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-ingress-http.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-ingress-grpc.yaml