name: "Release to Development"
concurrency:
  group: dev
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v2
      - name: Replace env placeholders
        run: |
          sed -i "s/#{GITHUB_SHA}/$GITHUB_SHA/g" ./.k8s/dev/bimble-backend-depl.yaml
          sed -i "s/#{VERSION}/${GITHUB_SHA::7}/g" ./Makefile
      - name: Build and push docker image
        run: |
          docker build -t container-registry.infra.svc.cluster.local/bimble-backend:${GITHUB_SHA}-dev .
          docker push container-registry.infra.svc.cluster.local/bimble-backend:${GITHUB_SHA}-dev
      - name: Deploy to Dev Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            kubectl apply -f ./.k8s/dev/bimble-backend-depl.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-svc.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-ingress-http.yaml
            kubectl apply -f ./.k8s/dev/bimble-backend-ingress-grpc.yaml