name: "Deploy Feature to Cluster"
concurrency:
  group: bim-feature-${{ github.ref	}}
  cancel-in-progress: true
  
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Extract feature ID, check validity
        run: |
          FEATURE_ID=$(echo ${{ github.head_ref }} | grep -oP '(feature\/)\K(BIM)-\d+(?=-)' | tr 'A-Z' 'a-z')
          if [[ -z $FEATURE_ID ]]; then
            echo "::error branch must be name feature/BIM-123-lorem-ipsum" 
            exit 1
          fi
          echo "FEATURE_ID=$FEATURE_ID" >> $GITHUB_ENV
      - name: Set feature ID
        run: |
          sed -i "s/#{FEATURE_ID}/$FEATURE_ID/g" ./.k8s/feature/bimble-backend-depl.yaml
          sed -i "s/#{FEATURE_ID}/$FEATURE_ID/g" ./.k8s/feature/bimble-backend-svc.yaml
          sed -i "s/#{FEATURE_ID}/$FEATURE_ID/g" ./.k8s/feature/bimble-backend-ingress-grpc.yaml
          sed -i "s/#{FEATURE_ID}/$FEATURE_ID/g" ./.k8s/feature/bimble-backend-ingress-http.yaml
          sed -i "s/#{FEATURE_ID}/$FEATURE_ID/g" ./files/config/feature.yaml
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push docker image
        run: |
          docker build -t huseinnashr/bimble-backend:${FEATURE_ID}-feature .
          docker push huseinnashr/bimble-backend:${FEATURE_ID}-feature
      - name: Deploy to Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_PROD }}
        with:
          args: |
            kubectl apply -f ./.k8s/feature/bimble-backend-depl.yaml
            kubectl apply -f ./.k8s/feature/bimble-backend-svc.yaml
            kubectl apply -f ./.k8s/feature/bimble-backend-ingress-http.yaml
            kubectl apply -f ./.k8s/feature/bimble-backend-ingress-grpc.yaml