name: "Deploy to Feature"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.head_ref }}
      - name: Extract, validate and assign feature id
        run: |
          FEATURE_ID=$(echo ${{ github.head_ref }} | grep -oP '(feature\/)\K(BIM)-\d+(?=-)' | tr 'A-Z' 'a-z')
          if [[ -z $FEATURE_ID ]]; then
            echo "::error branch must be name feature/BIM-123-lorem-ipsum" 
            exit 1
          fi
          echo "FEATURE_ID=$FEATURE_ID" >> $GITHUB_ENV
      - name: printout feature_id
        run: |
          echo $FEATURE_ID