name: "Release to Production"

on:
  push:
    tags: 
    - '*-production-secret'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: |
          sed -i "s/#{RESOURCE_SQL_DATABASE_PASSWORD}/$secrets.RESOURCE_SQL_DATABASE_PASSWORD/g" ./.k8s/prod/bimble-backend-secret.yaml
      - name: Apply changes to secret
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_PROD }}
        with:
          args: |
            kubectl apply -f ./.k8s/prod/bimble-backend-secret.yaml
            kubectl rollout restart deployment bimble-backend-depl -n bimble